 const gaugeCO = new RadialGauge({
    renderTo: "gauCO",
    colorValueBoxRectEnd: "#333",
    colorValueBoxRect: "#222",
    valueBoxBorderRadius: 0,
    colorNeedleCircleInnerEnd: "#222",
    colorNeedleCircleInner: "#111",
    colorNeedleCircleOuterEnd: "#111",
    colorNeedleCircleOuter: "#333",
    colorNeedleShadowDown: "#333",
    colorBorderInnerEnd: "#333",
    colorBorderInner: "#111",
    colorBorderMiddleEnd: "#111",
    colorBorderMiddle: "#222",
    colorBorderOuterEnd: "#111",
    colorBorderOuter: "#333",
    animationRule: "bounce",
    animationDuration: 1200,
    needleCircleInner: false,
    needleCircleOuter: true,
    needleCircleSize: 7,
    needleWidth: 2,
    needleType: "arrow",
    borders: true,
    borderShadowWidth: 0,
    colorPlate: "#222",
    colorNumbers: "#eee",
    colorUnits: "#ccc",
    colorTitle: "#eee",
    colorMinorTicks: "#ddd",
    colorMajorTicks: "#ddd",
  
    highlights: [
      {
        from: 0,
        to: 80,
        color: "rgba(0,255, 0, .8)",
      },
      {
        from: 80,
        to: 160,
        color: "rgba(255,0, 0, .7)",
      },
      {
        from: 160,
        to: 400,
        color: "rgba(255,255, 51, .8)",
      }
    ],
    valueInt: 2,
    valueDec: 1,
    strokeTicks: true,
    minorTicks: 2,
    majorTicks: [0, 80, 160, 240, 320,400],
    maxValue: 400,
    minValue: 0,
    title: "CO",
    units: "mg/m3",
   // height: 250,
    //width: 250,
  }).draw();

  //************************************************************************************************ */
  const gaugeNO2 = new RadialGauge({
    renderTo: "gauNO2",
    colorValueBoxRectEnd: "#333",
    colorValueBoxRect: "#222",
    valueBoxBorderRadius: 0,
    colorNeedleCircleInnerEnd: "#222",
    colorNeedleCircleInner: "#111",
    colorNeedleCircleOuterEnd: "#111",
    colorNeedleCircleOuter: "#333",
    colorNeedleShadowDown: "#333",
    colorBorderInnerEnd: "#333",
    colorBorderInner: "#111",
    colorBorderMiddleEnd: "#111",
    colorBorderMiddle: "#222",
    colorBorderOuterEnd: "#111",
    colorBorderOuter: "#333",
    animationRule: "bounce",
    animationDuration: 1200,
    needleCircleInner: false,
    needleCircleOuter: true,
    needleCircleSize: 7,
    needleWidth: 2,
    needleType: "arrow",
    borders: true,
    borderShadowWidth: 0,
    colorPlate: "#222",
    colorNumbers: "#eee",
    colorUnits: "#ccc",
    colorTitle: "#eee",
    colorMinorTicks: "#ddd",
    colorMajorTicks: "#ddd",
  
    highlights: [
      {
        from: 0,
        to: 10,
        color: "rgba(0,255, 0, .8)",
      },
      {
        from: 10,
        to: 20,
        color: "rgba(255,0, 0, .7)",
      }
    ],
    valueInt: 2,
    valueDec: 1,
    strokeTicks: true,
    minorTicks: 2,
    majorTicks: [0, 5, 10, 15, 20],
    maxValue: 20,
    minValue: 0,
    title: "NO2",
    units: "mg/m3",
   // height: 250,
    //width: 250,
  }).draw();

 
  //************************************************************************************************ */
  const gaugeO3 = new RadialGauge({
    renderTo: "gauO3",
    colorValueBoxRectEnd: "#333",
    colorValueBoxRect: "#222",
    valueBoxBorderRadius: 0,
    colorNeedleCircleInnerEnd: "#222",
    colorNeedleCircleInner: "#111",
    colorNeedleCircleOuterEnd: "#111",
    colorNeedleCircleOuter: "#333",
    colorNeedleShadowDown: "#333",
    colorBorderInnerEnd: "#333",
    colorBorderInner: "#111",
    colorBorderMiddleEnd: "#111",
    colorBorderMiddle: "#222",
    colorBorderOuterEnd: "#111",
    colorBorderOuter: "#333",
    animationRule: "bounce",
    animationDuration: 1200,
    needleCircleInner: false,
    needleCircleOuter: true,
    needleCircleSize: 7,
    needleWidth: 2,
    needleType: "arrow",
    borders: true,
    borderShadowWidth: 0,
    colorPlate: "#222",
    colorNumbers: "#eee",
    colorUnits: "#ccc",
    colorTitle: "#eee",
    colorMinorTicks: "#ddd",
    colorMajorTicks: "#ddd",
  
    highlights: [
      {
        from: 0,
        to: 180,
        color: "rgba(0,255, 0, .8)",
      },
      {
        from:180,
        to: 200,
        color: "rgba(255,0, 0, .7)",
      }
    ],
    valueInt: 2,
    valueDec: 1,
    strokeTicks: true,
    minorTicks: 2,
    majorTicks: [0, 40, 80, 120,160,200],
    maxValue: 200,
    minValue: 0,
    title: "O3",
    units: "mg/m3",
    //height: 250,
    //width: 250,
  }).draw();

  //********************************************************************** */
  const gaugeSO2 = new RadialGauge({
    renderTo: "gauSO2",
    colorValueBoxRectEnd: "#333",
    colorValueBoxRect: "#222",
    valueBoxBorderRadius: 0,
    colorNeedleCircleInnerEnd: "#222",
    colorNeedleCircleInner: "#111",
    colorNeedleCircleOuterEnd: "#111",
    colorNeedleCircleOuter: "#333",
    colorNeedleShadowDown: "#333",
    colorBorderInnerEnd: "#333",
    colorBorderInner: "#111",
    colorBorderMiddleEnd: "#111",
    colorBorderMiddle: "#222",
    colorBorderOuterEnd: "#111",
    colorBorderOuter: "#333",
    animationRule: "bounce",
    animationDuration: 1200,
    needleCircleInner: false,
    needleCircleOuter: true,
    needleCircleSize: 7,
    needleWidth: 2,
    needleType: "arrow",
    borders: true,
    borderShadowWidth: 0,
    colorPlate: "#222",
    colorNumbers: "#eee",
    colorUnits: "#ccc",
    colorTitle: "#eee",
    colorMinorTicks: "#ddd",
    colorMajorTicks: "#ddd",
  
    highlights: [
      {
        from: 0,
        to: 10,
        color: "rgba(0,255, 0, .8)",
      },
      {
        from:10,
        to: 20,
        color: "rgba(255,0, 0, .7)",
      }
    ],
    valueInt: 2,
    valueDec: 1,
    strokeTicks: true,
    minorTicks: 2,
    majorTicks: [0, 4, 8, 12,16,20],
    maxValue: 20,
    minValue: 0,
    title: "SO2",
    units: "mg/m3",
   // height: 250,
   // width: 250,
  }).draw();

  //********************************************************************** */
  const gaugePM10 = new RadialGauge({
    renderTo: "gauPM10",
    colorValueBoxRectEnd: "#333",
    colorValueBoxRect: "#222",
    valueBoxBorderRadius: 0,
    colorNeedleCircleInnerEnd: "#222",
    colorNeedleCircleInner: "#111",
    colorNeedleCircleOuterEnd: "#111",
    colorNeedleCircleOuter: "#333",
    colorNeedleShadowDown: "#333",
    colorBorderInnerEnd: "#333",
    colorBorderInner: "#111",
    colorBorderMiddleEnd: "#111",
    colorBorderMiddle: "#222",
    colorBorderOuterEnd: "#111",
    colorBorderOuter: "#333",
    animationRule: "bounce",
    animationDuration: 1200,
    needleCircleInner: false,
    needleCircleOuter: true,
    needleCircleSize: 7,
    needleWidth: 2,
    needleType: "arrow",
    borders: true,
    borderShadowWidth: 0,
    colorPlate: "#222",
    colorNumbers: "#eee",
    colorUnits: "#ccc",
    colorTitle: "#eee",
    colorMinorTicks: "#ddd",
    colorMajorTicks: "#ddd",
  
    highlights: [
      {
        from: 0,
        to: 70,
        color: "rgba(0,255, 0, .8)",
      },
      {
        from1:70,
        to: 100,
        color: "rgba(255,0, 0, .7)",
      }
    ],
    valueInt: 2,
    valueDec: 1,
    strokeTicks: true,
    minorTicks: 2,
    majorTicks: [0, 20, 40, 60,80,100],
    maxValue: 100,
    minValue: 0,
    title: "PM10",
    units: "mg/m3",
   // height: 250,
   // width: 250,
  }).draw();